#!/bin/sh

# Mount necessary fs
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# Load the PCI serial driver
modprobe 8250_exar

# Release modems from reset
devmem 0x53000000 8 0xff

# Set up eth0
ip link set dev eth0 address 00:08:00:12:34:56
ip link set eth0 up
udhcpc -i eth0

echo
echo "ModemFinder booted"
echo

# Start a shell
exec setsid cttyhack /bin/sh
